### ISSUE TITLE
A Zinnia module to perform the retrieval checks

### ISSUE THREAD

**Issue by juliangruber** [filecoin-station/spark#1]
- [x] We can use HTTP API to ask the Orchestrator about the job to perform.
- [x] Retrieve the CID using the IPFS Gateway or Saturn CDN, making HTTP requests via the Fetch API. (We will rework this in the following iterations.)
- [x] Submit retrieval logs & metrics to Ingester
    - [x] Look at what Saturn and Rhea/Lassie is including in their logs.
    - [x] TTFB, TTLB, error rates, retry count, download speed, etc.
    - [x] Talk to Will and Lauren what data will be useful to them. Maybe we can make this dynamically configurable?
    - [x] Let’s start with the easy metrics we can get from the Fetch API only.
    - [x] When Station reports the job outcome to the Ingester, it includes `JobId` and `WalletAddress` in the payload. https://github.com/filecoin-station/spark-api/pull/14
    - [x] We will need to mock/stub Orchestrator and Ingester for testing.
- [x] The module will be deployed to Filecoin Stations, it will replace the placeholder peer-checker module https://github.com/filecoin-station/core/pull/142

For now, no verification of the retrieval content, as this will be covered with Lassie later

Estimate: 5 days

**Comment by juliangruber** [comment]
Station integration is missing

**Comment by bajtos** [comment]
Maybe we should keep this issue open until the change is released on Station Desktop?
