### ISSUE TITLE
Shorten Spark rounds to 20 minutes

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/spark#50]
- Change the round length from 60 minutes to 20 minutes - call `setNextRoundLength(40)`
- Change the round reward to 1/3 to preserve the monthly reward 1000 FIL - call `setRoundReward(0.4566210046)`

**Comment by juliangruber** [comment]
Updated the live contract

**Comment by bajtos** [comment]
There are two more parameters we need to review and tweak after changing the round length:
- TASKS_PER_ROUND (currently 4000)
- MAX_TASKS_PER_NODE (currently 60)

See https://github.com/filecoin-station/spark-api/blob/dbb6606d46dee2a12164f4b5cb901086dffdcdd5/lib/round-tracker.js#L11-L14

I decided to keep these values unchanged.
- We will test the same number of CIDs per round, which means we will test 3x more CIDs each hour/day/week
- We increase the load on SPs 3x. Retrieval bandwidth per hour will increase from ~45MB to ~135MB and number of requests from ~1.6m to ~5m per hour.

While 5m req/hour may seem high, the clients randomly choose one of 4000 CIDs to test, which means our network sends 0.34 req/sec/CID.

**Comment by juliangruber** [comment]
> 0.34 req/sec/CID

This _seems_ high. So in 3 seconds we will have tested the entire CID set?

**Comment by juliangruber** [comment]
I don't have an informed opinion here. I'm happy to wait until someone complains, if that ever happens. Do you have a number how many req/sec the average storage provider will be receiving?

**Comment by bajtos** [comment]
> I don't have an informed opinion here. I'm happy to wait until someone complains, if that ever happens.

👍🏻 

> Do you have a number how many req/sec the average storage provider will be receiving?

We are not tracking this information right now. We don't have SP<->retrieval association yet. But maybe we can use `provider_address` as the proxy value and calculate how many requests we send to the same `provider_address`. WDYT?

**Comment by juliangruber** [comment]
That would be useful yes!

**Comment by bajtos** [comment]
Created https://github.com/filecoin-station/roadmap/issues/64 and added it to M4.2.
